/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ApiIntegrationService } from "../apiIntegration.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ApiIntegrationCreateInput } from "./ApiIntegrationCreateInput";
import { ApiIntegration } from "./ApiIntegration";
import { ApiIntegrationFindManyArgs } from "./ApiIntegrationFindManyArgs";
import { ApiIntegrationWhereUniqueInput } from "./ApiIntegrationWhereUniqueInput";
import { ApiIntegrationUpdateInput } from "./ApiIntegrationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ApiIntegrationControllerBase {
  constructor(
    protected readonly service: ApiIntegrationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ApiIntegration })
  @nestAccessControl.UseRoles({
    resource: "ApiIntegration",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createApiIntegration(
    @common.Body() data: ApiIntegrationCreateInput
  ): Promise<ApiIntegration> {
    return await this.service.createApiIntegration({
      data: data,
      select: {
        apiKey: true,
        createdAt: true,
        description: true,
        endpoint: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ApiIntegration] })
  @ApiNestedQuery(ApiIntegrationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ApiIntegration",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async apiIntegrations(
    @common.Req() request: Request
  ): Promise<ApiIntegration[]> {
    const args = plainToClass(ApiIntegrationFindManyArgs, request.query);
    return this.service.apiIntegrations({
      ...args,
      select: {
        apiKey: true,
        createdAt: true,
        description: true,
        endpoint: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ApiIntegration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ApiIntegration",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async apiIntegration(
    @common.Param() params: ApiIntegrationWhereUniqueInput
  ): Promise<ApiIntegration | null> {
    const result = await this.service.apiIntegration({
      where: params,
      select: {
        apiKey: true,
        createdAt: true,
        description: true,
        endpoint: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ApiIntegration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ApiIntegration",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateApiIntegration(
    @common.Param() params: ApiIntegrationWhereUniqueInput,
    @common.Body() data: ApiIntegrationUpdateInput
  ): Promise<ApiIntegration | null> {
    try {
      return await this.service.updateApiIntegration({
        where: params,
        data: data,
        select: {
          apiKey: true,
          createdAt: true,
          description: true,
          endpoint: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ApiIntegration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ApiIntegration",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteApiIntegration(
    @common.Param() params: ApiIntegrationWhereUniqueInput
  ): Promise<ApiIntegration | null> {
    try {
      return await this.service.deleteApiIntegration({
        where: params,
        select: {
          apiKey: true,
          createdAt: true,
          description: true,
          endpoint: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
