/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FinancialInsightService } from "../financialInsight.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FinancialInsightCreateInput } from "./FinancialInsightCreateInput";
import { FinancialInsight } from "./FinancialInsight";
import { FinancialInsightFindManyArgs } from "./FinancialInsightFindManyArgs";
import { FinancialInsightWhereUniqueInput } from "./FinancialInsightWhereUniqueInput";
import { FinancialInsightUpdateInput } from "./FinancialInsightUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FinancialInsightControllerBase {
  constructor(
    protected readonly service: FinancialInsightService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FinancialInsight })
  @nestAccessControl.UseRoles({
    resource: "FinancialInsight",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFinancialInsight(
    @common.Body() data: FinancialInsightCreateInput
  ): Promise<FinancialInsight> {
    return await this.service.createFinancialInsight({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        content: true,
        createdAt: true,
        id: true,
        insightType: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [FinancialInsight] })
  @ApiNestedQuery(FinancialInsightFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "FinancialInsight",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async financialInsights(
    @common.Req() request: Request
  ): Promise<FinancialInsight[]> {
    const args = plainToClass(FinancialInsightFindManyArgs, request.query);
    return this.service.financialInsights({
      ...args,
      select: {
        content: true,
        createdAt: true,
        id: true,
        insightType: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FinancialInsight })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FinancialInsight",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async financialInsight(
    @common.Param() params: FinancialInsightWhereUniqueInput
  ): Promise<FinancialInsight | null> {
    const result = await this.service.financialInsight({
      where: params,
      select: {
        content: true,
        createdAt: true,
        id: true,
        insightType: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FinancialInsight })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FinancialInsight",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFinancialInsight(
    @common.Param() params: FinancialInsightWhereUniqueInput,
    @common.Body() data: FinancialInsightUpdateInput
  ): Promise<FinancialInsight | null> {
    try {
      return await this.service.updateFinancialInsight({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          content: true,
          createdAt: true,
          id: true,
          insightType: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FinancialInsight })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FinancialInsight",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFinancialInsight(
    @common.Param() params: FinancialInsightWhereUniqueInput
  ): Promise<FinancialInsight | null> {
    try {
      return await this.service.deleteFinancialInsight({
        where: params,
        select: {
          content: true,
          createdAt: true,
          id: true,
          insightType: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
